PROJECT: "AAN_dss"
DATASET:
  NAME: AAN
  MAX_LEN: 4000
  TEST_SIZE: 147085
  TRAIN_SIZE: 18089
  VAL_SIZE: 17436
MODEL:
  ACTIVATION: $torch.nn.GELU
  BIAS: True
  BIDIRECTIONAL: False
  DROPOUT: 0.
  ENCODING: embedding
  INPUT_SIZE: 256
  KERNEL_VERSION: exp
  N_LAYERS: 1
  NAME: DSS
  NORMALIZATION: batch_norm
  POOLING: average
  PRENORM: True
  SEED: [1112] #[712,8,93,74,812]
  USE_LENGTHS: True
TRAIN:
  BATCH_SIZE: 2
  DISPLAY_EPOCH: True
  DISPLAY_EVERY: null
  LOSS_FN: $torch.nn.CrossEntropyLoss  #$torch.nn.BCEWithLogitsLoss  #BCE if the output of the model is unidimensional
  LOSS_CONFIG: null
  METRICS: {'accuracy': $torchmetrics.Accuracy} #{'accuracy': $torchmetrics.classification.BinaryAccuracy}
  METRICS_CONFIG:
    task: multiclass
    num_classes: 2
  N_EPOCHS: 25
  OPTIMIZER: $torch.optim.AdamW
  OPTIMIZER_CONFIG:
    lr: [0.002]
    weight_decay: 0.
  SCHEDULER: $torch.optim.lr_scheduler.ReduceLROnPlateau
  SCHEDULER_CONFIG:
    patience: 20
  TORCH_DEVICE: cpu
  TRACK_NORMS: False
  USE_TQDM: False
  USE_WANDB: False